### ISSUE TITLE
问下安装问题

### ISSUE THREAD

**Issue by hotmop** [newnius/short-link#2]
自定义config.inc.php＆static/config.js   
什么意思 是修改文件为数据库信息 还是什么意思？没弄明白

**Comment by newnius** [comment]
`config.inc.php` 里面修改 Mysql、Redis、Oauth、Site 这几部分的参数，`static/config.js` 里面修改网址信息。

如果是本地部署的话，Oauth部分可以用这个：

```
define('OAUTH_SITE', 'https://quickauth.newnius.com');
define('OAUTH_CLIENT_ID', 'XgaII6NxeE08LtKB');
define('OAUTH_CLIENT_SECRET', 'L9hdi4dQToM0GsDLtcYYQ3k4ZDEjuGVOtPS3nOVKlo6cxLcVjH9TqvmTBiHAgLp2');
```

**Comment by hotmop** [comment]
有没有简便的方式啊  有点没听明白

**Comment by hotmop** [comment]
能不能出个中文教程

**Comment by newnius** [comment]
第一步 把整个项目代码clone到服务器上，作为网站根目录（子目录方式没有测试过）；
服务器我用的是 Apache，需要启用伪静态，可以参考[Apache 启用rewrite伪静态/重写功能](https://blog.newnius.com/apache-enable-mod-rewrite.html)。
如果你是用 Nginx + fpm的话，可以参考 [#3](https://github.com/newnius/short-link/issues/3)修改Nginx配置。

第二步 修改`static/config.js`，主要是修改 `BASE_URL` 参数，改成你自己的网址，这个参考默认值改，应该没啥问题；

第三步 把 `config-sample.inc.php` 重命名为 `config.inc.php`，然后修改这个文件里面的参数，主要有这么几个必须修改的：

| 参数 | 说明 |
| --- | --- |
| DB_HOST | Mysql 数据库的host，一般是是localhost |
| DB_PORT | Mysql 数据库的端口，一般是3306 |
| DB_NAME | Mysql 数据库的库名，这需要你自己在数据库里新建一个，名字随意，一致就行 |
| DB_USER | Mysql数据库连接用的用户名 |
| DB_PASSWORD | Mysql数据库连接密码 |
| REDIS_HOST | Redis数据库host，一般是localhost |
| REDIS_PORT| Redis数据库监听端口，一般是6379 |
| BASE_URL | 网站根网址，参考默认值改 |
| OAUTH_CLIENT_ID | Oauth登陆id |
| OAUTH_CLIENT_SECRET | Oauth登陆key |

后面两个需要到 [QuickAuth](https://quickauth.newnius.com/)网站申请，具体步骤如下
1. 注册并登陆（Sign up & Sign in）
2. 左边菜单选择`Sites`目录，然后`Add`，写上你的域名，不要有http和后面的路径，然后`Save`
3. 点击域名列表后面的`View`，`ClientID`对应的就是上面的`OAUTH_CLIENT_ID`，`ClientSecret`对应的是上面的`OAUTH_CLIENT_SECRET`

第四步 在浏览器访问你的 `install.php`，前面的域名需要自己补全一下，如`http://example.com/install.php`，应该会提示几条`Success`。

这样应该就装完了，如果还有什么问题的话可以继续提问，文档确实写的还不够清晰。

**Comment by hotmop** [comment]
謝謝 已經非常清晰  當時具體情況其實是js里那個文件不是明白，這次寫的很清晰了。再次感謝
