### ISSUE TITLE
无法打开页面

### ISSUE THREAD

**Issue by jakkpop** [newnius/short-link#24]
之前一直可以，但有一段时间没有留意，然后重新打开却发现再也无法打开页面。
Auths那里删了就无法重新添加了
![微信图片_20220105011512](https://user-images.githubusercontent.com/30544872/148098473-5b3d8554-b010-4001-a2e3-d87396c84c27.png)

sites那里是正常的
![微信截图_20220105011543](https://user-images.githubusercontent.com/30544872/148098592-bca4229a-620c-40b9-9e12-4de17672d1e9.png)

但一打开就如图所示，空白页面，但又没有错误信息显示
![微信截图_20220105011703](https://user-images.githubusercontent.com/30544872/148098650-a9e71f86-db8f-4f1c-9417-e7e2a048f99c.png)

所以询问一下作者，这个是什么问题。
尝试多次都无法修复。

**Comment by jakkpop** [comment]
已经解决。
之前为了省事用了Let‘s Encrypt的一键ssl，但似乎有些问题，无法Auths认证。
用了其他的ssl，已经可以了。

**Comment by newnius** [comment]
同时自建了QuickAuth和short-link么？letsencrypt的ssl根证书去年10月份到期了，老的设备会无法访问。

**Comment by jakkpop** [comment]
> 同时自建了QuickAuth和short-link么？letsencrypt的ssl根证书去年10月份到期了，老的设备会无法访问。

是的，两个都建了。感觉letsencrypt的ssl证书更新过，感觉应该是没问题的，其他子域名也是用的同一个证书，是正常使用。
但QuickAuth就跳转不了。

**Comment by newnius** [comment]
授权登录按照oauth协议的，可能是服务器版本比较老，上面的证书过期了，电脑访问应该没问题。
