### ISSUE TITLE
请问一下已经要经过quickauth.newnius.com的登陆认证吗？

### ISSUE THREAD

**Issue by jakkpop** [newnius/short-link#5]

**Comment by jakkpop** [comment]
已解决：查到quickauth源码

**Comment by newnius** [comment]
你好，授权登陆相关的代码在 https://github.com/newnius/short-link/blob/master/auth.php 这个文件里，修改相关的信息即可。

以及 https://github.com/newnius/short-link/blob/master/static/script.js
https://github.com/newnius/short-link/blob/master/user.logic.php
